= Manuel opérateur pour la numérisation du règlement
d’urbanisme

Version du 16/02/2021


== Sommaire
 * <<Introduction>>
 * <<Etape 1. Installer les pré-requis>>
 * <<Etape 2. Copie du PLU original>>
 * <<Etape 3. Mise en page>>
 * <<Etape 4. Renseigner les métadonnées>>
 * <<Etape 5. Identifier les zones>>
 * <<Etape 6. Identifier les prescriptions>>
 * <<Etape 7. Enregistrement>>

:toc:

== Introduction

=== Contexte

Le CNIG développe actuellement un format de structuration des règlements d'urbanisme afin de les rendre plus facilement exploitables par des machines.
L'objectif à long terme de ce standard est de développer des applications pour faciliter l'instruction des demandes de permis de construire par exemple.

Afin de faciliter la transformation d'un PLU dans ce nouveau format, un outil a été créé à partir de LibreOffice. Il s'agit d'un premier outil simple, réservé aux PLU. Sa mise en oeuvre pour un PLUi n'est pas conseillée.

=== Objectif

Ce manuel opérateur est destiné aux collectivités territoriales et leurs prestataires pour effectuer la numérisation de leur PLU. Il vous donnera toutes les étapes nécessaires à cette numérisation.
L’objectif de la numérisation du PLU est de créer un règlement interactif et exploitable informatiquement (au contraire d’un document au format PDF qui est figé et inexploitable informatiquement). Grâce à cette numérisation, divers projets peuvent être mis en place, notamment l’accès aux règles d’urbanisme applicables à une parcelle sur le Géoportail de l’Urbanisme. D’autres applications peuvent exploiter ces données informatisées dans le but de modéliser les contraintes d’urbanisme.
La numérisation du règlement d’urbanisme repose uniquement sur des logiciels libres.


=== Exemple

Vous trouverez un exemple de PLU réalisé sous libreOffice https://github.com/cnigfr/structuration-reglement-urbanisme/blob/master/outils/conversion-FODT-2-CNIG/exemple%20PLU_Jaleyrac.fodt[ici]


== Définitions

Champ : Un champ est une fonction qui permet d’ajouter du contenu dynamique au
règlement écrit à structurer. Nous utilisons les champs de variable dans Writer de
LibreOffice pour définir les différentes zones et prescriptions auxquelles s’applique
une partie du règlement.
On les trouve dans Writer de LibreOffice en effectuant Insertion/Champ/Autre
champ/Variables et comme attributs de données géographiques dans le DU
dématérialisé suivant le standard CNIG.
Métadonnée : Les fiches de métadonnées sont un outil essentiel pour le catalogage
des différents documents présents sur le Géoportail de l'Urbanisme, c’est une liste
de données qui permet d’identifier le document vis à vis des autres documents sur
GPU et d’y associer une zone géographique. C’est en quelque sorte la carte
d’identité du document, permettant de le cataloguer et d’y donner accès.
PLU : Plan Local d’Urbanisme.
Nous ne transformerons que la partie réglementaire textuelle donc nous n'aurons
besoin que de la pièce Règlement écrit. Nous aurons aussi besoin des pièces
graphiques (zonages et prescriptions) sous forme vectorielle (par exemple au format
shapefile), qui sont conformes au standard CNIG PLU.
PLUi : PLU intercommunal. De même que pour le PLU, nous ne transformons que la
pièce Règlement écrit, et nous aurons besoin des mêmes pièces graphiques.
Prescription : Une prescription se présente dans le standard CNIG PLU sous la
forme d'une information surfacique, linéaire ou ponctuelle qui apparaît sur les
documents graphiques du PLU. Une prescription qui se superpose à une zone du
document d'urbanisme exerce en général une contrainte supplémentaire au
règlement de la zone. Les prescriptions ont également des champs.
Pour identifier les différentes prescriptions, on utilise les pièces graphiques sous
forme vectorielle, dans la table des attributs de la table PRESCRIPTION, l’ensemble
des prescriptions sont renseignées dans la colonne "libellé" des différentes couches
(prescription de surfaciques, linéaires et ponctuelles).
Zone : Les zones d’un PLU(i) ou le zonage correspondent aux différentes zones
d’urbanisation, et des règles différentes s’appliquent à ses différentes zones.
Pour identifier les différentes zones, on utilise les pièces graphiques sous
forme vectorielle, dans la table des attributs, l’ensemble des zones sont renseignées
dans la colonne "libellé" de la couche des zonages.
2
Style : Les styles de Writer (LibreOffice) définissent les
caractéristiques de mise en forme des éléments qui composent
le document LibreOffice
Nous nous en servons pour définir la hiérarchie du document.
(Titre 1 englobe tous les Titres 2 jusqu’au Titre 1 suivant, etc...).
Pour le contenu du paragraphe, on utilise le style “Corps du
texte”. Ci-contre, nous pouvons voir la table des styles qui
contient les styles qui vont nous intéresser : les styles Titre
numérotés, et le style corps du texte.
Titre : Un titre est défini par un style. On les utilise pour
hiérarchiser le document, on utilise uniquement les titres
numérotés définis par défaut dans LibreOffice. Le Titre 1, par
exemple, correspond au titre d’un chapitre du règlement écrit
(ex : “Chapitre 1 : Dispositions communes à toutes les zones).


== Etape 1. Installer les pré-requis

Logiciel Libre Office Writer.
Télécharger le fichier https://github.com/cnigfr/structuration-reglement-urbanisme/blob/master/outils/conversion-FODT-2-CNIG/template%20FODT2CNIG%20vb%C3%A9ta1.fodt[template FODT2CNIG].

== Etape 2. Copie du PLU original

La première étape consiste à copier le contenu du PDF.

Pour cela, sélectionner l'intégralité du PDF (Ctrl+A) et le copier (Ctrl+C).
Ouvrir le template Libre Office "template FODT2CNIG" et coller le texte du PDF au format texte brut dans Libre Office (Ctrl+Alt+Maj+V).

Note : dans le cas ou le fichier PDF est une image scannée, le texte n'est pas sélectionnable. Il convient de convertir l'image en texte en utilisant la reconnaissance de caractère (ou OCR) dont il existe de nombreux outils en-ligne gratuits.

Attention, il est important de ne pas copier la mise en page pour les raisons suivantes :

* ne pas perturber l'étape ultérieure de transformation
* obtenir une homogénéïté des règlements

Ensuite, il convient d'enlever le texte superflu.
Ex: 

* les en-têtes et pieds-de-page qui vont être répétées à chaque page.
* Les illustration et textes "décoratifs" et qui n'ont pas valeur réglementaire.

Il est également possible que des sauts de lignes ait été rajoutés lors de la copie.
Il est souhaitable de supprimer ces sauts de lignes indésirables.

=== Copie des images

Il faut maintenant réintégrer les images souhaitées dans le texte car elle n'auront pas été copiées.
Pour cela :

Dans le PDF, sélectionner l'image et l'enregistrer sur le disque dur. Si ce n'est pas possible, essayez de retrouver l'image d'origine
en contactant la personne qui a réalisé le PDF, sinon effectuer une capture d'écran. Attention, la capture d'écran doit être réalisée avec un affichage supérieur ou égal à 100%, sinon l'image ne sera pas d'assez bonne qualité.
Note : les images doivent être enregistrées dans un dossier "ressources" situé au même emplacement que le fichier Libre Office et avoir un nom unique.

Puis, insérer l'image dans le texte à l'endroit souhaité (glisser-déposer dans Libre Office).

Ensuite, il faut nommer l'image avec le même nom que le fichier. Pour cela, effectuer un clic droit sur l'image dans Libre Office et cliquer sur Propriétés. Dans Nom, indiquez le nom du fichier que vous venez d'enregistrer *avec l'extension : par exemple, image1.jpg ou toto.png)*. Vous pouvez également renseigner le champ Alternative qui servira a afficher un libellé sur l'image (propriété Alt en HTML).

== Etape 3. Mise en page

Il convient maintenant de faire une mise en page sommaire. Il ne s'agit pas de recréer exactement la même mise en page que le PDF. En effet,
l'outil de conversion ne prend en charge qu'un nombre limité d'options.
Les options prises en charge sont les suivantes :

* Titres
* Images
* gras
* souligné
* italique
* hyperliens
* tableaux

=== Titres

Pour définir un titre, cliquez sur le texte du titre et modifier le style :
dans la liste déroulante, sélectionner le niveau de titre qui convient. Par exemple, le style Titre 1, Titre 2, etc.

*Attention : Votre document doit impérativement commencer par un titre de niveau 1 (style = Titre 1 sous libre office) et il ne doit pas y avoir de trou dans l'enchaînement des titres. Par exemple, Si, sous un titre de niveau 2, il doit obligatoirement y avoir un titre de niveau 3, etc.*

=== hyperliens 

Dans Libre Office, sélectionner le texte contenant l'hyperlien et sélectionner Insérsion/Hyperlien dans le menu (ou Ctrl+K).

* S'il s'agit d'une URL externe, copier-coller l'URL dans le champ URL
* S'il s'agit d'un lien interne (pour faire un renvoi), sélectionner Document/Cible et sélectionner le titre correspondant.

== Etape 4. Renseigner les métadonnées

Le fichier template FODT2CNIG est pré-enregistré avec des métadonnées.

Pour les modifier, aller dans Fichier/Propriétés/propriétés personnalisées, et renseignez les valeurs suivantes :

* id : URL du règlement en ligne ou, sinon, le nom du règlement (pièce écrite du standard CNIG PLU). Ex : 44712_reglement_20041103
* nom : nom du règlement d’urbanisme. Le nom doit être explicite et mentionner le nom de la collectivité. Ex : Règlement écrit du PLUi de Lille Métropole
* typeDoc : Correspond au champ TYPEDOC de la classe DOC_URBA du Standard CNIG PLU. Limité aux valeurs PLU et PLUI.
* lien : lien vers le fichier de métadonnées du document d’urbanisme. Si le fichier de métadonnées est disponible en-ligne, mettre le lien de la fiche de métadonnées, sinon, le lien vers le document d’urbanisme téléchargeable sur le GPU. Ex : http://www.geoportail-urbanisme.gouv.fr/atom/datasetfeed/DU_44183.xml

Important : afin de voir les variables qui vont être ajoutées par la suite, il est important de changer l'affichage des champs.
Dans Libre Office, aller dans le menu Affichage et cliquer sur Nom des champs (ou Ctrl+F9). 
Attention : une fois cette modification effectuée, elle modifiera également l'affichage de tous vos autres document office (par exemple, les renvois ou numéros de page ne s'afficheront pas correctement). Il suffit alors de refaire la même opération pour revenir à l'affichage normal (ou Ctrl+F9).

== Etape 5. Identifier les zones

Lorsqu'un PLU est chargé dans le géoportail de l'urbanisme (GPU), il est accompagné d'une couche SIG ZONE_URBA définissant les frontières du
zonage du PLU. Ce zonage correspond dans le règlement écrit à des chapitres voir à des paragraphes spécifiques. Il convient de les identifier
à l'aide de l'outil Libre Office.

=== Dans les titres

Lorsqu'un zonage est commun à toutes les parties d'un chapitre :
Dans ce cas, cliquez à la fin du titre concerné (juste après le dernier caractère du titre, dans la même ligne) et ajouter une variable :
Insertion/Champs/Autres champs. Sélectionner la variable "idZone" et renseigner la Valeur de la façon suivante :

LIBELLE de la classe ZONE_URBA du standard CNIG PLU  correspondant à la zone décrite dans ce chapitre, ou la valeur « porteeGenerale » si le titre s’applique à toutes les zones.
La valeur peut contenir plusieurs zones séparées par des virgules. Ex :	"UG,1AU" ou "A,N".

L'identification de la commune est également nécessaire pour le bon fonctionnement de l'outil.
Pour cela, cliquez à la fin du titre concerné (après la variable "idZone" que vous venez d'ajouter) et ajouter une variable :

Insertion/Champs/Autres champs. Sélectionner la variable "inseeCommune" et renseigner le code INSEE de la commune concernée. Si plusieurs communes sont concernées, les codes INSEE séparés par une virgule. Ex: "69382,69383".

Remarque : il n'est pas nécessaire de définir une variable pour tous les titres. En effet, si la valeur est la même pour tous les sous-titres d'un titre, alors
ne la définir que pour le titre de plus haut niveau.

=== Dans les paragraphes

Lorsqu'un paragraphe concerne un zonage spécifique différent du reste du chapitre, par exemple, le secteur UGa de la zone UG.

Dans ce cas, cliquer au début du paragraphe concerné (juste avant le premier caractère du paragraphe, dans la même ligne) et ajouter une variable :
Insertion/Champs/Autres champs. Sélectionner la variable "idZoneStart" et renseigner la Valeur de la zone ou du secteur de zone concerné.

Note, cette valeur doit également correspondre à un LIBELLE de la classe ZONE_URBA.

Puis, cliquer à la fin du paragraphe concerné (juste après le dernier caractère du paragraphe, dans la même ligne) et ajouter une variable :
Insertion/Champs/Autres champs. Sélectionner la variable "idZoneEnd" et renseigner la Valeur de la zone ou du secteur de zone concerné.

Remarque : si aucune variable n'est définie à un paragraphe, alors celui-ci portera les mêmes informations que le titre auquel il appartient. Dans l'exemple précédent : UG.

== Etape 6. Identifier les prescriptions

=== Dans les titres

Lorsqu'une prescription est commune à toutes les parties d'un chapitre :
Dans ce cas, cliquez à la fin du titre concerné (juste après le dernier caractère du titre, dans la même ligne) et ajouter une variable :
Insertion/Champs/Autres champs. Sélectionner la variable "idPresc" et renseigner un identifiant de la prescription correspondant au libellé d'un objet d'une des couches PRESCRIPTION_PCT, PRESCRIPTION_SURF et PRESCRIPTION_LIN. Ex : "Mur et haie à protéger"

La valeur peut contenir plusieurs prescriptions séparées par des virgules. Ex : "Mur et haie à protéger,Continuité écologique linéaire".


Note : Dans la version définitive, il s'agira d'un nouveau champ à ajouter dans les couches PRESCRIPTION_PCT, PRESCRIPTION_SURF et PRESCRIPTION_LIN. En effet, actuellement aucun champ des tables PRESCRIPTION_XXX ne permet d'être utilisé comme identifiant.

Si le chapitre ne contient pas de prescription, alors ne pas mettre de variable idPresc.

Si le chapitre est commun à toutes les prescriptions, alors la variable "idPresc" doit avoir pour valeur "porteeGenerale".

=== Dans les paragraphes

Lorsqu'un paragraphe concerne une prescription spécifique différent du reste du chapitre :
Dans ce cas, cliquer au début du paragraphe concerné (juste avant le premier caractère du paragraphe, dans la même ligne) et ajouter une variable :
Insertion/Champs/Autres champs. Sélectionner la variable "idPrescStart" et renseigner l'identifiant de la prescription comme pour les titres (paragraphe ci-dessus).

Ensuite, cliquer à la fin du paragraphe concerné (juste après le dernier caractère du paragraphe, dans la même ligne) et ajouter une variable :
Insertion/Champs/Autres champs. Sélectionner la variable "idPrescEnd" et renseigner l'identifiant de la prescription.

Remarque : si aucune variable n'est définie à un paragraphe, alors celui-ci portera les mêmes informations que le titre auquel il appartient. Par exemple : "porteeGenerale"



== Etape 7. Enregistrement

Une fois le fichier terminé, vous pouvez l'enregistrer (en conservant le format fodt), le zipper avec le dossier ressources contenant les images et l'envoyer à stephane.garcia@ign.fr.

N'oubliez pas de remonter les problèmes rencontrés en créant des "issues" dans GitHub (https://docs.github.com/en/github/managing-your-work-on-github/creating-an-issue). Ce n'est pas la peine de le faire dans le corps du mail.


== Test (facultatif)
Pour les utilisateurs avancés :
Vous pouvez vous-même tester si le résultat est compatible avec le schéma CNIG règlement DU.
Pour cela, lancer dans l'ordre les processus XSL fodt2CNIG-1, 2 et 3 sur le fichier FODT ainsi créé et comparer le résultat avec le schéma XSD situé ici :  https://github.com/cnigfr/structuration-reglement-urbanisme/blob/master/schemas/reglementDU.xsd

Vous pouvez alors remonter les éventuelles erreurs en créant des "issues" dans GitHub.
