= Guide d'utilisation de l'outil de conversion FODT vers le format CNIG règlement d'urbanisme

Version béta 1

== Introduction

Le CNIG développe actuellement un format de structuration des règlements d'urbanisme afin de les rendre plus facilement exploitables par des machines.
L'objectif à long terme de ce standard est de développer des applications pour faciliter l'instruction des demandes de permis de construire par exemple.

Afin de faciliter la transformation d'un PLU dans ce nouveau format, un outil a été créé à partir de LibreOffice. Et nous le mettons à disposition afin de
permettre à tous de pouvoir tester le format de structuration des règlements d'urbanisme du CNIG en cours de développement.

== Objectif

L'objectif de ce guide est de donner toutes les étapes pour transformer un PLU dans le nouveau format.
Cela nous permettra de voir si le nouveau format est bien adapté aux différents PLU et de le corriger si nécessaire.

== A qui est destiné ce guide ?

Ce guide est destiné à toute personne ou collectivité souhaitant participer à l'élaboration du nouveau format de structuration des règlements d'urbanisme
et tester la transformation de son PLU au nouveau format.

== Support

Si vous constatez des problèmes à l'utilisation de l'outil ou du présent guide, merci de créer une nouvelle "issue" dans GitHub.

== 1. Copie du PLU original

La première étape consiste à copier le contenu du PDF dans le fichier "template FODT2CNIG".
Pour cela, sélectionner l'intégralité du PDF (Ctrl+A) et copier le au format texte brut dans Libre Office.
Attention, il est important de ne pas copier la mise en page pour les raisons suivantes :
* ne pas perturber l'étape ultérieure de transformation
* obtenir une homogénéïté des règlements

Ensuite, il convient d'enlever le texte superflu.
Ex: 
* les en-têtes et pied de page qui vont être répétées à chaque page.
* Les illustration et textes "décoratifs" et qui n'ont pas valeur réglementaire.

=== Copie des images

Il faut maintenant réintégrer les images souhaitées dans le texte car elle n'auront pas été copiées.
Pour cela :
* Dans le PDF, sélectionner l'image et l'enregistrer sur le disque dur (si ce n'est pas possible, essayez de retrouver l'image d'origine
en contactant la personne qui a réalisé le PDF, sinon effectuer une capture d'écran). Attention, la capture d'écran doit être réalisée avec un affichage supérieur ou égal à 100%, sinon l'image ne sera pas d'assez bonne qualité.
Note : les images doivent être enregistrées dans un dossier "ressources" situé au même emplacement que le fichier Libre Office et avoir un nom unique.


== 1. Mise en page




